/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_rgb_free(a: number): void;
export function rgb_new(a: number, b: number, c: number): number;
export function rgb_toHSI(a: number): number;
export function __wbg_hsi_free(a: number): void;
export function hsi_new(a: number, b: number, c: number): number;
export function hsi_toRGB(a: number): number;
export function __wbgt_rgb_to_hsi_0(a: number): void;
export function __wbgt_his_to_rgb_1(a: number): void;
export function wasmalert(a: number, b: number): void;
export function takeNumberSliceBySharedRef(a: number, b: number): void;
export function makeImageData(a: number): number;
export function letsPapperNoise(a: number): number;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h205400d0d0703f14(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function wasm_bindgen__convert__closures__invoke0_mut__h217185c2ad0ee8a4(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h1440b4edf1917acc(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__hc485a18a66aedbd4(a: number, b: number, c: number, d: number): void;
