[package]
authors = ["swzhxx <549909896@qq.com>"]
edition = "2018"
name = "slam-wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
getrandom = {version = "0.2", features = ["js"]}
nalgebra = "0.27.0"
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
nshare = {version = "0.7.0", features = ["nalgebra", "ndarray"]}
num-traits = "0.2"
slam-core = {path = "./../slam-core"}
wasm-bindgen = "0.2.63"
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = {version = "0.1.6", optional = true}

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = {version = "0.4.5", optional = true}

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.web-sys]
features = ["ImageData", "console"]
version = "0.3.51"

[dependencies.js-sys]
version = "0.3.51"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
